#pragma config(Motor,  port1,           rightTop,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           r1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           r2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           r3,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           l3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           l2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           l1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftBoth,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightBot,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		//Chassis joystick control
		motor[r1] = vexRT[Ch2]*19/20;
		motor[r2] = vexRT[Ch2]*19/20;
		motor[r3] = vexRT[Ch2]*19/20;
		motor[l3] = vexRT[Ch3]*19/20;
		motor[l2] = vexRT[Ch3]*19/20;
		motor[l1] = vexRT[Ch3]*19/20;

		//Lift control
		if(vexRT[Btn5U] == 1)
		{
			motor[leftBoth] = -100;
			motor[rightBot] = 100;
			motor[rightTop] = 100;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[leftBoth] = 100;
			motor[rightBot] = -100;
			motor[rightTop] = -100;
		}
		else
		{
			motor[leftBoth] = 0;
			motor[rightBot] = 0;
			motor[rightTop] = 0;
		}
		if(vexRT[Btn6U] == 1)
		{
			motor[claw] = 75;
		}
		else if(vexRT[Btn6D]== 1)
		{
			motor[claw] = -75;
		}
		else
		{
			motor[claw] = 0;
		}
	}
}
